name: Convert all v1
on: 
  push:
    paths:
      - "trigger.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: running transform
        run: bash dtabf2dtabf_id_all.sh
        env:
          changes: ${{ steps.files.outputs.all }}
      - name: test transform
        run: bash test.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: transform all
