on: push
name: Docx To Tei
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: running transform
        run: . docx2tei-actions.sh
        env:
          changes: ${{ steps.files.outputs.all }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: docx2xml transform
